export function roundToNearestNthDecimal(value, decimalIndex) {
  const exponent = 10 ** decimalIndex;

  return Math.round(value * exponent) / exponent;
}

// Generated by ChatGPT
export function roundToNSignificantDigits(num, n) {
  if (num === 0) return 0;
  // Calculate the magnitude of the number
  const magnitude = Math.floor(Math.log10(Math.abs(num))) + 1;
  // Calculate the scale to round the number
  const scale = 10 ** (n - magnitude);
  // Round the number to the nearest integer, then scale back to the original magnitude
  return Math.round(num * scale) / scale;
}

export function formatNumWithCommas(number) {
  return Number(number).toLocaleString();
}
